theme: jekyll-theme-leap-day
show_downloads: true
github:
  zip_url: https://github.com/heschy/Blender-Configuration-Skript/zipball/main
  tar_url: https://github.com/heschy/Blender-Configuration-Skript/tarball/mai
